Repository NeTEx-CEN/NeTEx, pull requests merged in 2021-08, with the labels that each got.

#200 Remove redundant AccessVehicleEquipmentGroup2
  xsd/netex_framework/netex_reusableComponents/netex_equipmentVehiclePassenger_version.xsd
Labels: bug

#202 Fix MinimumHeight, MaximumHeight to LengthType
  xsd/netex_part_3/part3_fares/netex_usageParameterEligibility_version.xsd
Labels: bug

#199 Change SosPhones to SosPanel
  xsd/netex_part_1/part1_ifopt/netex_ifopt_equipmentPassenger_version.xsd
Labels: bug

#197 Typo's
  xsd/netex_part_3/part3_fares/netex_accessRightParameter_version.xsd
Labels: typo

#201 Fix BoardingHeight to LengthType
  xsd/netex_framework/netex_reusableComponents/netex_equipmentVehiclePassenger_version.xsd
Labels: bug

#187 Add enumerations for pushchair
  xsd/netex_framework/netex_reusableComponents/netex_facility_support.xsd
Labels: needs documentation update

#207 Update epip_common_profile.xml
  examples/standards/epip/epip_common_profile.xml
Labels: typo
