Repository NeTEx-CEN/NeTEx, pull requests merged in 2021-09, with the labels that each got.

#222 Remove typo
  xsd/netex_framework/netex_genericFramework/netex_place_version.xsd
Labels: typo

#230 Fix documentation of CrossingEquipmentGroup/VisualGuidanceBands
  xsd/netex_part_1/part1_ifopt/netex_ifopt_equipmentAccess_version.xsd
Labels: typo

#231 Fix Id type for GeneralSign
  xsd/netex_part_1/part1_ifopt/netex_ifopt_equipmentSigns_version.xsd
Labels: bug

#236 Fix doc of AssistanceFacilityList
  xsd/netex_framework/netex_reusableComponents/netex_facility_version.xsd
Labels: typo

#238 Fix typo
  xsd/netex_part_1/part1_ifopt/netex_ifopt_path_version.xsd
Labels: typo

#239 Fix typo and doc of SharpsDisposal
  xsd/netex_part_1/part1_ifopt/netex_ifopt_equipmentPassenger_version.xsd
Labels: bug, typo

#240 Fix CounterService documentation
  xsd/netex_part_1/part1_ifopt/netex_ifopt_localService_version.xsd
Labels: typo

#237 Fix LuggageTrolleys documentation
  xsd/netex_part_1/part1_ifopt/netex_ifopt_localService_version.xsd
Labels: typo
