Repository NeTEx-CEN/NeTEx, pull requests merged in 2022-04, with the labels that each got.

#298 EPIAP quay boarding positions enhancement
  xsd/netex_part_1/part1_ifopt/netex_ifopt_stopPlace_version.xsd
Labels: needs documentation update

#285 OnwardServiceLinkView has a Distance, OnwardTimingLinkView should he too.
  xsd/netex_part_1/part1_tacticalPlanning/netex_timingPattern_version.xsd
Labels: bug, needs documentation update

#215 Improve information about ScheduledStopPoints
  xsd/netex_part_1/part1_networkDescription/netex_flexibleNetwork_version.xsd
  xsd/netex_part_1/part1_tacticalPlanning/netex_servicePattern_version.xsd
  xsd/netex_part_1/part1_tacticalPlanning/netex_stopAssignment_version.xsd
Labels: enhancement

#68 Slovenian timetable with EU Profile
  examples/functions/timetable/Netex_09.2_Bus_SimpleTimetable_Slovenia.xml
Labels: example

#69 COR proposal: PenaltyPolicyTypeEnumeration change Checkin value to CheckIn to be in line with spec.
  xsd/netex_part_3/part3_fares/netex_usageParameterCharging_support.xsd
Labels: bug

#315 Add Length and Width on StopPlaceSpaceGroup
  xsd/netex_part_1/part1_ifopt/netex_ifopt_stopPlace_version.xsd
Labels: enhancement, needs documentation update

#314 Improve passenger information equipment
  xsd/netex_part_1/part1_ifopt/netex_ifopt_equipmentTicketing_version.xsd
  xsd/netex_part_1/part1_tacticalPlanning/netex_passengerInformationEquipment_version.xsd
Labels: change-request, needs documentation update

#276 Update netex_ifopt_stopPlace_support.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_stopPlace_support.xsd
Labels: needs documentation update

#267 Align temporalValidityParameters with spec
  xsd/netex_part_3/part3_fares/netex_accessRightParameter_version.xsd
Labels: needs documentation update

#255 Allow multiple gml:Polygons associated to a Zone
  xsd/gml/geometryAggregates-extract-v3_2_1.xsd
  xsd/gml/geometryPrimitives-extract-v3_2_1.xsd
  xsd/gml/gml_extract_all_objects_v_3_2_1.xsd
  xsd/netex_framework/netex_genericFramework/netex_zone_version.xsd
Labels: needs documentation update

#229 Should allow for explicit referencing of TariffZone subtype FareZone
  xsd/netex_framework/netex_genericFramework/netex_zone_support.xsd
Labels: enhancement

#265 Extension of AccessibilityLimitation for EPIAP
  xsd/netex_framework/netex_genericFramework/netex_accessibility/netex_acsb_limitations.xsd
Labels: needs documentation update

#144 Add new construction GroupOfTariffzones
  examples/functions/grouping/Netex_GroupingExample_General_01.xml
  xsd/NeTEx_publication.xsd
  xsd/NeTEx_publication_timetable.xsd
  xsd/netex_framework/netex_genericFramework/netex_zone_version.xsd
  xsd/netex_part_1/part1_frames/netex_siteFrame_version.xsd
  xsd/netex_part_3/part3_fares/netex_accessRightParameter_version.xsd
Labels: change-request, needs documentation update

#59 Comment NL28
  xsd/netex_part_1/part1_networkDescription/netex_line_version.xsd
Labels: needs documentation update

#55 Comment-SBB20
  xsd/netex_part_1/part1_tacticalPlanning/netex_servicePattern_version.xsd
Labels: needs documentation update

#57 Comment SBB23
  xsd/netex_framework/netex_utility/netex_utility_types.xsd
Labels: needs documentation update

#110 Change TypeOfFuelEnumeration to match official NeTEx specification
  xsd/netex_framework/netex_reusableComponents/netex_vehicleType_support.xsd
Labels: needs documentation update

#141 Add usage validity start/end time for element access
  xsd/netex_part_3/part3_salesTransactions/netex_customerPurchasePackage_version.xsd
Labels: change-request, needs documentation update

#132 Add animalsAllowed to NuisanceFacilityEnumeration
  xsd/netex_framework/netex_reusableComponents/netex_facility_support.xsd
Labels: needs-example, needs documentation update

#323 Fix master
  xsd/netex_framework/netex_utility/netex_utility_types.xsd
Labels: bug

#320 Typo allInclusivePrice
  xsd/netex_framework/netex_reusableComponents/netex_facilityUic_support.xsd
Labels: bug

#117 Make MainPartRef non-mandatory for JourneyPart (JourneyPartGroup)
  xsd/netex_part_2/part2_journeyTimes/netex_coupledJourney_version.xsd
Labels: needs documentation update

#148 Add optional TimebandRef and ServiceCalendarRef to TemporalValidityParametersGroup
  xsd/netex_part_3/part3_fares/netex_accessRightParameter_version.xsd
Labels: needs-example, needs documentation update

#321 Examples taptsi / TypeOfPlug
  NeTEx.spp
  examples/standards/tap_tsi/Document1.txt
  examples/standards/tap_tsi/TAP-SKDUPD-example1-basic.xml
  examples/standards/tap_tsi/TAP-SKDUPD-example1.xml
  examples/standards/tap_tsi/TAP-SKDUPD-example2.1-Classic_train.xml
  examples/standards/tap_tsi/TAP-SKDUPD-example2.2-Coach_group.xml
  examples/standards/tap_tsi/TAP-SKDUPD-example2.3-Leo_Express.xml
  examples/standards/tap_tsi/TAP-SKDUPD-example2.4-Load_and_Unload.xml
  examples/standards/tap_tsi/TAP-SKDUPD-example2.5-Interchange.xml
  examples/standards/tap_tsi/TAP-SKDUPD-example2.6-Check_In.xml
  examples/standards/tap_tsi/TAP-SKDUPD-example2.7-Tariff_and_Reservation.xml
  examples/standards/tap_tsi/TAP-SKDUPD-example2.7-Tarrif_and_Reservation.xml
  examples/standards/tap_tsi/TAP-SKDUPD-example2.xml
  examples/standards/tap_tsi/TAP-TSDUPD-example1.xml
  examples/standards/tap_tsi/TAP-TSDUPD-example2.1-Hilleroed.xml
  examples/standards/tap_tsi/TAP-TSDUPD-example2.2-Milano.xml
  examples/standards/tap_tsi/TAP-TSDUPD-example2.3-Piedmont.xml
  examples/standards/tap_tsi/TAP-TSDUPD-example2.4-Paris.xml
  examples/standards/tap_tsi/TAP-TSDUPD-example2.xml
  xsd/netex_framework/netex_reusableComponents/netex_nm_equipmentEnergy_version.xsd
Labels: enhancement, needs documentation update, example

#168 Fix AccessEquipmentRef
  xsd/netex_framework/netex_reusableComponents/netex_equipmentVehiclePassenger_support.xsd
  xsd/netex_framework/netex_reusableComponents/netex_equipmentVehiclePassenger_version.xsd
  xsd/netex_framework/netex_reusableComponents/netex_equipment_support.xsd
  xsd/netex_framework/netex_reusableComponents/netex_equipment_version.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_equipmentAccess_support.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_equipmentAccess_version.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_equipmentSigns_support.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_equipmentSigns_version.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_equipmentTicketing_version.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_equipmentWaiting_support.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_equipmentWaiting_version.xsd
Labels: bug

#65 Accessibility extension FR49
  xsd/netex_part_1/part1_ifopt/netex_ifopt_equipmentAccess_support.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_equipmentAccess_version.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_equipmentSigns_version.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_localService_version.xsd
Labels: needs documentation update

#277 Update netex_equipmentPlace_version.xsd
  xsd/netex_framework/netex_reusableComponents/netex_equipmentPlace_version.xsd
Labels: bug, needs documentation update

#343 Cr51_remains
  xsd/netex_part_1/part1_tacticalPlanning/netex_stopAssignment_version.xsd
  xsd/netex_part_2/part2_journeyTimes/netex_vehicleJourney_version.xsd
Labels: needs documentation update

#351 All wheelChairXXX to wheelchairXXX and WheelChair to Wheelchair
  examples/functions/site/Netex_21_Sites_Parking_2.xml
  examples/functions/timetable/Netex_10_Rail_SplittingJoiningTimetable.xml
  examples/functions/timetable/Netex_11_Rail_CompoundTrain.xml
  examples/functions/timetable/Netex_21_Rail_NetworkTimetable_eurostar.xml
  examples/standards/norway/stops/StopPlace-with-equipment-and-parking_example.xml
  xsd/netex_framework/netex_reusableComponents/netex_equipmentVehiclePassenger_version.xsd
  xsd/netex_framework/netex_reusableComponents/netex_serviceRestrictions_support.xsd
Labels: bug, needs documentation update
