Repository NeTEx-CEN/NeTEx, pull requests merged in 2023-09, with the labels that each got.

#490 Remove VehicleJourneyStopAssignmentsInFrame_RelStructure
  xsd/netex_part_2/part2_journeyTimes/netex_vehicleJourney_version.xsd
Labels: bug

#498 Remove unused xsd files.
  xsd/netex_framework/netex_genericFramework/netex_contact_support.xsd
  xsd/netex_framework/netex_genericFramework/netex_contact_version.xsd
Labels: bug

#483 Fix issue #469
  xsd/NX.xsd
Labels: bug

#499 Fix typo
  xsd/netex_part_1/part1_tacticalPlanning/netex_routingConstraint_version.xsd
Labels: typo

#500 Fixing enum problems
  xsd/netex_framework/netex_reusableComponents/netex_trainElement_support.xsd
  xsd/netex_framework/netex_reusableComponents/netex_vehicleSeating_support.xsd
Labels: typo

#501 Doc version status enumeration
  xsd/netex_framework/netex_responsibility/netex_version_support.xsd
Labels: typo

#411 Extended-DatedVehicleJourney+Replace-PR368
  xsd/NeTEx_publication.xsd
  xsd/NeTEx_publication_timetable.xsd
  xsd/netex_part_2/part2_journeyTimes/netex_datedVehicleJourney_support.xsd
  xsd/netex_part_2/part2_journeyTimes/netex_datedVehicleJourney_version.xsd
Labels: needs documentation update

#504 Add qr code
  xsd/netex_part_3/part3_fares/netex_typeOfTravelDocument_support.xsd
Labels: enhancement, needs documentation update

#506 Update netex_nm_vehicleMeetingPointAssignment_support.xsd
  xsd/netex_part_5/part5_nd/netex_nm_vehicleMeetingPointAssignment_support.xsd
Labels: typo

#365 BeaconEquipment added and example VehicleType modeling for EPIAP
  NeTEx.spp
  examples/standards/epiap/EPIAP_Accessibility_Chur_V08_vehicletypes.xml
  xsd/netex_part_1/part1_ifopt/netex_ifopt_equipmentPassenger_support.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_equipmentPassenger_version.xsd
Labels: change-request, needs documentation update

#507 Fix improve mode
  xsd/netex_framework/netex_genericFramework/netex_place_version.xsd
  xsd/netex_framework/netex_reusableComponents/netex_mode_support.xsd
  xsd/netex_framework/netex_reusableComponents/netex_submode_version.xsd
Labels: needs documentation update

#510 Fix passenger information equipment list
  xsd/netex_framework/netex_reusableComponents/netex_facility_version.xsd
  xsd/netex_part_1/part1_tacticalPlanning/netex_passengerInformationEquipment_version.xsd
Labels: bug

#511 Fix typo's
  xsd/netex_part_1/part1_ifopt/netex_ifopt_site_version.xsd
Labels: typo
