Repository NeTEx-CEN/NeTEx, pull requests merged in 2023-10, with the labels that each got.

#516 Introduce VAT
  xsd/netex_framework/netex_genericFramework/netex_organisation_version.xsd
Labels: enhancement

#509 Removing duplicate enumeration (thanks to David)
  xsd/netex_framework/netex_reusableComponents/netex_facility_support.xsd
  xsd/netex_framework/netex_reusableComponents/netex_nm_equipmentEnergy_support.xsd
  xsd/netex_framework/netex_utility/netex_units.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_vehicleStopping_support.xsd
Labels: bug

#524 Fix railIslandPlatform
  xsd/netex_part_1/part1_ifopt/netex_ifopt_stopPlace_support.xsd
Labels: bug

#520 Rail dated journey fix without example updates
  xsd/NeTEx_publication.xsd
  xsd/NeTEx_publication_timetable.xsd
  xsd/netex_part_2/part2_journeyTimes/netex_datedVehicleJourney_support.xsd
  xsd/netex_part_2/part2_journeyTimes/netex_datedVehicleJourney_version.xsd
Labels: needs documentation update

#527 Addition of TypeOfProductCategory to JourneyPart
  xsd/netex_part_2/part2_journeyTimes/netex_coupledJourney_version.xsd
Labels: needs documentation update

#519 Addition of reviews to comments about
  xsd/netex_part_5/part5_fm/netex_nm_individualTraveller_support.xsd
  xsd/netex_part_5/part5_fm/netex_nm_individualTraveller_version.xsd
  xsd/netex_part_5/part5_sj/netex_nm_singleJourneyService_version.xsd
Labels: needs documentation update
