Repository NeTEx-CEN/NeTEx, pull requests merged in 2023-11, with the labels that each got.

#534 Fix #533
  xsd/netex_part_1/part1_ifopt/netex_ifopt_equipmentAccess_version.xsd
Labels: bug, needs documentation update

#528 Addition of Alighting and Boarding request methods
  xsd/netex_part_1/part1_tacticalPlanning/netex_servicePattern_support.xsd
  xsd/netex_part_1/part1_tacticalPlanning/netex_servicePattern_version.xsd
Labels: enhancement, needs documentation update

#543 Redo pull #336
  xsd/netex_framework/netex_genericFramework/netex_assignment_version.xsd
Labels: typo

#525 Changes to booking arrangement
  examples/functions/bookingArrangements/generalframe.xml
  xsd/NeTEx_publication.xsd
  xsd/netex_framework/netex_frames/netex_resourceFrame_version.xsd
  xsd/netex_framework/netex_reusableComponents/netex_serviceRestrictions_support.xsd
  xsd/netex_framework/netex_reusableComponents/netex_serviceRestrictions_version.xsd
  xsd/netex_part_1/part1_ifopt/netex_assistanceBooking_version.xsd
  xsd/netex_part_1/part1_networkDescription/netex_flexibleNetwork_version.xsd
  xsd/netex_part_1/part1_tacticalPlanning/netex_servicePattern_version.xsd
  xsd/netex_part_2/part2_journeyTimes/netex_flexibleService_version.xsd
  xsd/netex_part_2/part2_journeyTimes/netex_serviceJourney_version.xsd
  xsd/netex_part_3/part3_fares/netex_usageParameterBooking_version.xsd
  xsd/netex_part_5/part5_rc/netex_nm_mobilityService_version.xsd
Labels: enhancement, needs documentation update

#530 Addition of contracts
  xsd/netex_framework/netex_frames/netex_resourceFrame_version.xsd
  xsd/netex_framework/netex_responsibility/netex_responsibilitySet_version.xsd
  xsd/netex_framework/netex_responsibility/netex_responsibility_support.xsd
Labels: enhancement, needs documentation update

#544 Implement privateCodes, deprecate PrivateCode, replace #403
  examples/functions/privateCodes/01-privateCodes.xml
  xsd/netex_framework/netex_genericFramework/netex_grouping_version.xsd
  xsd/netex_framework/netex_genericFramework/netex_organisation_version.xsd
  xsd/netex_framework/netex_genericFramework/netex_pointAndLinkSequence_version.xsd
  xsd/netex_framework/netex_responsibility/netex_responsibilitySet_version.xsd
  xsd/netex_framework/netex_responsibility/netex_responsibility_version.xsd
  xsd/netex_framework/netex_responsibility/netex_typeOfValue_version.xsd
  xsd/netex_framework/netex_responsibility/netex_validityCondition_version.xsd
  xsd/netex_framework/netex_reusableComponents/netex_dayType_version.xsd
  xsd/netex_framework/netex_reusableComponents/netex_equipment_version.xsd
  xsd/netex_framework/netex_reusableComponents/netex_notice_version.xsd
  xsd/netex_framework/netex_reusableComponents/netex_serviceCalendar_version.xsd
  xsd/netex_framework/netex_reusableComponents/netex_transportOrganisation_version.xsd
  xsd/netex_framework/netex_reusableComponents/netex_vehicleType_version.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_stopPlace_support.xsd
  xsd/netex_part_1/part1_networkDescription/netex_activation_version.xsd
  xsd/netex_part_1/part1_networkDescription/netex_line_version.xsd
  xsd/netex_part_1/part1_tacticalPlanning/netex_servicePattern_version.xsd
  xsd/netex_part_1/part1_tacticalPlanning/netex_stopAssignment_version.xsd
  xsd/netex_part_1/part1_tacticalPlanning/netex_timeDemandType_version.xsd
  xsd/netex_part_2/part2_journeyTimes/netex_interchange_version.xsd
  xsd/netex_part_2/part2_vehicleService/netex_vehicleService_version.xsd
  xsd/netex_part_3/part3_fares/netex_farePrice_version.xsd
  xsd/netex_part_3/part3_fares/netex_fareProduct_version.xsd
  xsd/netex_part_3/part3_fares/netex_fareSeries_version.xsd
  xsd/netex_part_3/part3_fares/netex_fareStructureElement_version.xsd
  xsd/netex_part_3/part3_fares/netex_fareStructure_version.xsd
  xsd/netex_part_3/part3_fares/netex_geographicStructureFactor_version.xsd
  xsd/netex_part_3/part3_fares/netex_qualityStructureFactor_version.xsd
  xsd/netex_part_3/part3_fares/netex_salesOfferPackage_version.xsd
  xsd/netex_part_3/part3_fares/netex_timeStructureFactor_version.xsd
  xsd/netex_part_3/part3_parkingTariff/netex_parkingTariff_version.xsd
  xsd/netex_part_3/part3_salesTransactions/netex_customerPurchasePackage_version.xsd
  xsd/netex_part_3/part3_salesTransactions/netex_travelDocument_version.xsd
Labels: enhancement, needs documentation update

#547 Fix epiap example validation
  .github/scripts/validate-examples.sh
Labels: enhancement

#554 Gradients are in degrees
  xsd/netex_part_1/part1_ifopt/netex_ifopt_equipmentAccess_version.xsd
Labels: bug

#540 Remove OpeningNecessaryForce
  xsd/netex_part_1/part1_ifopt/netex_ifopt_equipmentAccess_version.xsd
Labels: bug, needs documentation update, hygiene

#545 Enh driver permit
  xsd/netex_framework/netex_genericFramework/netex_organisation_version.xsd
  xsd/netex_framework/netex_genericFramework/netex_place_version.xsd
  xsd/netex_framework/netex_reusableComponents/netex_facility_support.xsd
  xsd/netex_framework/netex_reusableComponents/netex_facility_version.xsd
  xsd/netex_framework/netex_reusableComponents/netex_mode_support.xsd
  xsd/netex_framework/netex_reusableComponents/netex_nm_equipmentEnergy_support.xsd
  xsd/netex_framework/netex_reusableComponents/netex_submode_version.xsd
  xsd/netex_framework/netex_reusableComponents/netex_vehicleType_support.xsd
  xsd/netex_framework/netex_reusableComponents/netex_vehicleType_version.xsd
  xsd/netex_framework/netex_utility/netex_units.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_site_version.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_vehicleStopping_support.xsd
  xsd/netex_part_1/part1_tacticalPlanning/netex_passengerInformationEquipment_version.xsd
  xsd/netex_part_5/part5_nd/netex_nm_vehicleMeetingPointAssignment_support.xsd
Labels: enhancement, needs documentation update

#557 Fix typo in `Netex_gtfs_exm1_CalendarDates_1.xml`
  examples/standards/gtfs/Netex_gtfs_exm1_CalendarDates_1.xml
Labels: typo

#291 Proposal for URI with an object reference.
  examples/functions/relations/test-01-main.xml
  examples/functions/relations/test-01-timetable.xml
  xsd/netex_framework/netex_responsibility/netex_relationship_support.xsd
Labels: enhancement, change-request, needs documentation update

#559 Relative level order optional
  xsd/netex_part_1/part1_ifopt/netex_ifopt_site_version.xsd
Labels: enhancement, needs documentation update
