Repository NeTEx-CEN/NeTEx, pull requests merged in 2023-12, with the labels that each got.

#583 fix documentation of StatusEnumeration
  xsd/netex_part_1/part1_tacticalPlanning/netex_passengerInformationEquipment_version.xsd
Labels: bug

#586 adapted documentation #472
  xsd/netex_framework/netex_reusableComponents/netex_topographicPlace_version.xsd
Labels: bug, needs documentation update

#585 Remove unused files.
  xsd/netex_part_1/netex_all_objects_infrastructureFrame.xsd
  xsd/netex_part_3/part3_PiQuery/netex_all_objects_part3_piQuery.xsd
  xsd/netex_part_3/part3_PiQuery/netex_piQuery_support.xsd
  xsd/netex_part_5/part5_nd/netex_nm_ParkingCapacityAssignment_support.xsd
  xsd/netex_part_5/part5_nd/netex_nm_ParkingCapacityAssignment_version.xsd
Labels: bug

#587 adapted documentation #472 (#586)
  xsd/netex_framework/netex_reusableComponents/netex_topographicPlace_version.xsd
Labels: enhancement

#589 clarifications in documentation for GroupTicket
  xsd/netex_part_3/part3_fares/netex_usageParameterEligibility_version.xsd
Labels: bug, needs documentation update

#581 Arrival instead Departure in JourneyFrequencyGroupGroup
  examples/functions/timetable/NeTEx_50_JourneyFrequencyGroup.xml
  xsd/netex_part_2/part2_journeyTimes/netex_vehicleJourneyFrequency_version.xsd
Labels: enhancement, needs documentation update, Transmodel

#580 Extend telecabin submode and better focu
  xsd/netex_framework/netex_reusableComponents/netex_submode_version.xsd
Labels: enhancement, needs documentation update

#607 Update netex_servicePattern_support.xsd
  xsd/netex_part_1/part1_tacticalPlanning/netex_servicePattern_support.xsd
Labels: bug

#582 FuelType and PropulsionType unbounded
  examples/functions/newModes/NewModes-ChauffeuredServiceExample.xml
  xsd/netex_framework/netex_reusableComponents/netex_vehicleType_support.xsd
  xsd/netex_framework/netex_reusableComponents/netex_vehicleType_version.xsd
Labels: enhancement, needs documentation update, group_decision_needed

#577 new enum values for large vehicles in transporters
  xsd/netex_framework/netex_reusableComponents/netex_submode_version.xsd
  xsd/netex_framework/netex_reusableComponents/netex_trainElement_support.xsd
Labels: change-request, needs documentation update

#606 Docu HeadwayUseEnumeration
  xsd/netex_part_2/part2_journeyTimes/netex_vehicleJourneyFrequency_support.xsd
Labels: needs documentation update

#579 id now mandatory for PassengerCapacity
  examples/functions/timetable/Netex_01.4_Bus_SimpleTimetable_WithConnection.xml
  examples/standards/noptis/NeTEx_Calendar_TimetableAndVehicleSchedule_PB2.xml
  xsd/netex_framework/netex_reusableComponents/netex_vehicleType_version.xsd
Labels: bug

#603 Remove datedcallz from next
  xsd/netex_part_2/part2_journeyTimes/netex_call_version.xsd
Labels: enhancement

#287 Remove redundant sequence
  xsd/netex_part_1/part1_tacticalPlanning/netex_timingPattern_version.xsd
Labels: enhancement

#596 Remove datedCalls, and when it is valid, make it Calls
  xsd/netex_part_2/part2_journeyTimes/netex_call_support.xsd
  xsd/netex_part_2/part2_journeyTimes/netex_call_version.xsd
  xsd/netex_part_2/part2_journeyTimes/netex_datedVehicleJourney_version.xsd
Labels: enhancement

#578 docu upgrade for stopPlaces
  xsd/netex_part_1/part1_ifopt/netex_ifopt_site_version.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_stopPlace_version.xsd
Labels: needs documentation update

#573 Fare profile enhancement zone in series
  examples/standards/efp/VVS_Fares_V1-ZoneSeries-nk3.xml
  examples/standards/efp/VVS_Fares_V1-nk1.xml
  examples/standards/efp/VVS_Fares_V1-nk2.xml
  examples/standards/efp/VVS_Fares_V1.xml
  xsd/NeTEx_publication.xsd
  xsd/netex_part_3/part3_fares/netex_fareSeries_support.xsd
  xsd/netex_part_3/part3_fares/netex_fareSeries_version.xsd
Labels: enhancement, needs documentation update

#366 Ramp equipment with maximal load and an explanation for Length for mobile ramps.
  xsd/netex_part_1/part1_ifopt/netex_ifopt_equipmentAccess_version.xsd
Labels: change-request, needs documentation update

#601 Integrate LineEquipment air conditioning
  examples/functions/timetable/Netex_01.1_Bus_SimpleTimetable_JourneysOnly.xml
  xsd/netex_framework/netex_reusableComponents/netex_facility_support.xsd
  xsd/netex_framework/netex_reusableComponents/netex_facility_version.xsd
Labels: enhancement, needs documentation update

#600 Make sure that the PassengerCategoryies and the PrivateMode are done in NeTEx, so that it works out.
  examples/functions/line/NeTEx_01_simple_line.xml
  xsd/netex_framework/netex_utility/netex_utility_types.xsd
  xsd/netex_part_1/part1_networkDescription/netex_line_version.xsd
  xsd/netex_part_3/part3_fares/netex_usageParameterEligibility_support.xsd
Labels: enhancement, needs documentation update, needs transmodel update

#595 Update description multi lingual string next
  xsd/netex_framework/netex_responsibility/netex_entity_version.xsd
  xsd/netex_framework/netex_responsibility/netex_versionDelta_version.xsd
  xsd/netex_framework/netex_reusableComponents/netex_vehicleType_version.xsd
Labels: bug

#388 Delfiplus extensions
  xsd/netex_framework/netex_reusableComponents/netex_equipmentVehiclePassenger_version.xsd
  xsd/netex_framework/netex_reusableComponents/netex_equipment_support.xsd
  xsd/netex_framework/netex_reusableComponents/netex_facility_support.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_stopPlace_support.xsd
Labels: enhancement, needs documentation update

#542 Enhance door control element height (Fix #541)
  examples/functions/stopPlace/Netex_10_StopPlace_withParking_1.xml
  xsd/netex_part_1/part1_ifopt/netex_ifopt_equipmentAccess_version.xsd
Labels: enhancement, needs documentation update

#618 Validityparameters transportmode cen 2
  examples/functions/fares/rail/Netex_era_crossborder_de.xml
  examples/functions/fares/rail/Netex_era_toc_uk.xml
  examples/standards/fxc/FX-PI-01_UK_MB_NETWORK_FARE_Metrorider-pass+others_20170101.xml
  examples/standards/fxc/uk_fxc_addon_HSP_plusbus.xml
  xsd/netex_part_3/part3_fares/netex_accessRightParameter_version.xsd
  xsd/netex_part_3/part3_fares/netex_calculationParameters_version.xsd
Labels: bug

#619 Adding projectionsto ServiceFrame
  examples/functions/patterns/Netex_KBIC_ParisNetwork_1.xml
  xsd/netex_framework/netex_genericFramework/netex_projection_version.xsd
  xsd/netex_part_2/part2_frames/netex_serviceFrame_version.xsd
Labels: enhancement, needs documentation update

#626 better docu for ServiceAlterationEnumeration
  xsd/netex_part_2/part2_journeyTimes/netex_serviceJourney_support.xsd
Labels: needs documentation update

#611 Create epiap_test_Crossing_Equipment.xml
  examples/standards/epiap/epiap_test_Crossing_Equipment.xml
Labels: example
