Repository NeTEx-CEN/NeTEx, pull requests merged in 2024-01, with the labels that each got.

#631 Remove unusual places for JourneyPatternViews
  xsd/netex_part_1/part1_tacticalPlanning/netex_journeyPattern_version.xsd
  xsd/netex_part_1/part1_tacticalPlanning/netex_servicePattern_version.xsd
Labels: bug

#621 Better definitions for telecabin by Nick
  xsd/netex_framework/netex_reusableComponents/netex_submode_version.xsd
Labels: needs documentation update

#624 Epiap accessibility path link enhancement (in next)
  examples/functions/stopPlace/Netex_04_Stops_SimpleStation_1.xml
  xsd/netex_part_1/part1_ifopt/netex_ifopt_path_support.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_path_version.xsd
Labels: change-request, needs documentation update

#627 Corrections to #525 changes to BOOKING ARRANGEMENTs and SERVCIE BOOKING ARRANGEMENTS
  examples/functions/newModes/NewModes-CarPoolingExample.xml
  examples/functions/stopPlace/FX-PI-01_UK_TBD_STOP-OFFER_910GWIMBLDN-accessibility_20140601.xml
  examples/standards/norway/vehicles/submodel-VehicleType.xml
  xsd/NeTEx_publication.xsd
  xsd/netex_framework/netex_frames/netex_resourceFrame_version.xsd
  xsd/netex_framework/netex_reusableComponents/netex_serviceRestrictions_support.xsd
  xsd/netex_framework/netex_reusableComponents/netex_serviceRestrictions_version.xsd
  xsd/netex_part_1/part1_ifopt/netex_assistanceBooking_version.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_path_support.xsd
  xsd/netex_part_1/part1_networkDescription/netex_flexibleNetwork_version.xsd
  xsd/netex_part_1/part1_networkDescription/netex_line_version.xsd
  xsd/netex_part_1/part1_tacticalPlanning/netex_servicePattern_version.xsd
  xsd/netex_part_2/part2_journeyTimes/netex_flexibleService_version.xsd
  xsd/netex_part_2/part2_journeyTimes/netex_serviceJourney_version.xsd
  xsd/netex_part_3/part3_fares/netex_usageParameterBooking_version.xsd
  xsd/netex_part_5/part5_rc/netex_nm_mobilityService_version.xsd
Labels: enhancement, needs documentation update

#616 fixing Operator/Authority choice in line
  xsd/netex_part_1/part1_networkDescription/netex_line_version.xsd
Labels: bug, needs documentation update

#598 Passenger capacity align with siri
  examples/functions/timetable/Netex_01.4_Bus_SimpleTimetable_WithConnection.xml
  xsd/netex_framework/netex_reusableComponents/netex_vehicleType_version.xsd
Labels: enhancement, needs documentation update

#614 PublicCode settled
  xsd/netex_framework/netex_genericFramework/netex_organisation_version.xsd
  xsd/netex_framework/netex_genericFramework/netex_zone_version.xsd
  xsd/netex_framework/netex_reusableComponents/netex_equipment_version.xsd
  xsd/netex_framework/netex_reusableComponents/netex_notice_version.xsd
  xsd/netex_framework/netex_utility/netex_utility_types.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_equipmentAccess_support.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_parking_support.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_site_version.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_stopPlace_support.xsd
  xsd/netex_part_1/part1_networkDescription/netex_line_version.xsd
  xsd/netex_part_1/part1_tacticalPlanning/netex_servicePattern_version.xsd
Labels: change-request, needs documentation update

#604 Drop Call-Z and DatedCall-Z as discussed in #463
  xsd/netex_part_2/part2_journeyTimes/netex_call_version.xsd
Labels: enhancement

#646 Correction of the resides annotation
  xsd/netex_part_3/part3_fares/netex_usageParameterEligibility_version.xsd
Labels: typo

#647 Typo's
  xsd/netex_framework/netex_utility/netex_utility_types.xsd
Labels: typo

#608 Enhancement service exclusions #391
  NeTEx.spp
  examples/functions/timetable/Netex_01.7_Bus_SimpleTimetable_RoutingConstraints.xml
  xsd/netex_part_1/part1_networkDescription/netex_line_version.xsd
  xsd/netex_part_1/part1_tacticalPlanning/netex_routingConstraint_version.xsd
  xsd/netex_part_3/part3_fares/netex_accessRightParameter_version.xsd
Labels: enhancement, needs documentation update
