Repository NeTEx-CEN/NeTEx, pull requests merged in 2024-09, with the labels that each got.

#764 Labelling v2.0 changes, second series
  xsd/netex_framework/netex_responsibility/netex_responsibility_support.xsd
  xsd/netex_framework/netex_responsibility/netex_validityCondition_support.xsd
  xsd/netex_framework/netex_reusableComponents/netex_dayType_propertiesOfDay.xsd
  xsd/netex_framework/netex_reusableComponents/netex_dayType_version.xsd
  xsd/netex_framework/netex_reusableComponents/netex_facility_support.xsd
  xsd/netex_framework/netex_reusableComponents/netex_serviceRestrictions_support.xsd
  xsd/netex_framework/netex_reusableComponents/netex_submode_version.xsd
  xsd/netex_framework/netex_reusableComponents/netex_trainElement_version.xsd
  xsd/netex_framework/netex_reusableComponents/netex_vehicleType_support.xsd
  xsd/netex_framework/netex_reusableComponents/netex_vehicleType_version.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_equipmentParking_support.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_parking_support.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_parking_version.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_site_support.xsd
  xsd/netex_part_1/part1_networkDescription/netex_line_version.xsd
  xsd/netex_part_1/part1_networkDescription/netex_networkRestriction_version.xsd
  xsd/netex_part_1/part1_tacticalPlanning/netex_routingConstraint_support.xsd
  xsd/netex_part_3/part3_fares/netex_accessRightParameter_version.xsd
  xsd/netex_part_3/part3_fares/netex_distanceMatrixElement_version.xsd
  xsd/netex_part_3/part3_fares/netex_fareConditionSummary_support.xsd
  xsd/netex_part_3/part3_fares/netex_fareConditionSummary_version.xsd
  xsd/netex_part_3/part3_fares/netex_fareProduct_support.xsd
  xsd/netex_part_3/part3_fares/netex_fareTable_version.xsd
  xsd/netex_part_3/part3_fares/netex_salesDistribution_support.xsd
  xsd/netex_part_3/part3_fares/netex_typeOfTravelDocument_support.xsd
  xsd/netex_part_3/part3_fares/netex_usageParameterBooking_version.xsd
  xsd/netex_part_3/part3_fares/netex_usageParameterCharging_support.xsd
  xsd/netex_part_3/part3_fares/netex_usageParameterEligibility_version.xsd
  xsd/netex_part_3/part3_fares/netex_usageParameterTravel_support.xsd
  xsd/netex_part_3/part3_frames/netex_salesTransactionFrame_version.xsd
  xsd/netex_part_3/part3_salesTransactions/netex_customerPaymentMeans_version.xsd
  xsd/netex_part_3/part3_salesTransactions/netex_customerPurchasePackage_version.xsd
  xsd/netex_part_3/part3_salesTransactions/netex_salesContract_support.xsd
  xsd/netex_part_3/part3_salesTransactions/netex_salesContract_version.xsd
  xsd/netex_part_3/part3_salesTransactions/netex_travelSpecificationSummary_version.xsd
  xsd/netex_part_5/part5_fm/netex_nm_accessCredentialsAssignment_version.xsd
  xsd/netex_part_5/part5_fm/netex_nm_usageParameterRental_version.xsd
  xsd/netex_part_5/part5_frames/netex_nm_mobilityJourneyFrame_version.xsd
  xsd/netex_part_5/part5_frames/netex_nm_mobilityServiceFrame_version.xsd
  xsd/netex_part_5/part5_nd/netex_nm_mobilityServiceConstraintZone_support.xsd
  xsd/netex_part_5/part5_nd/netex_nm_mobilityServiceConstraintZone_version.xsd
  xsd/netex_part_5/part5_nd/netex_nm_vehicleMeetingPlace_version.xsd
  xsd/netex_part_5/part5_sj/netex_nm_singleJourneyService_version.xsd
Labels: document has been updated

#778 Delete Full_PublicationDelivery_109_Oslo_morningbus_example.xml
  examples/standards/norway/Full_PublicationDelivery_109_Oslo_morningbus_example.xml
Labels: change-request

#781 Labelling v2.0 changes, third series
  xsd/netex_framework/netex_frames/netex_resourceFrame_version.xsd
  xsd/netex_framework/netex_genericFramework/netex_accessibility/netex_acsb_limitations.xsd
  xsd/netex_framework/netex_genericFramework/netex_zone_version.xsd
  xsd/netex_framework/netex_responsibility/netex_relationship_support.xsd
  xsd/netex_framework/netex_reusableComponents/netex_deckPlan_version.xsd
  xsd/netex_framework/netex_reusableComponents/netex_environment_support.xsd
  xsd/netex_framework/netex_reusableComponents/netex_equipmentVehiclePassenger_version.xsd
  xsd/netex_framework/netex_reusableComponents/netex_facility_support.xsd
  xsd/netex_framework/netex_reusableComponents/netex_modeOfOperation_support.xsd
  xsd/netex_framework/netex_reusableComponents/netex_modeOfOperation_version.xsd
  xsd/netex_framework/netex_reusableComponents/netex_mode_support.xsd
  xsd/netex_framework/netex_reusableComponents/netex_nm_fleetEquipment_version.xsd
  xsd/netex_framework/netex_reusableComponents/netex_serviceRestrictions_version.xsd
  xsd/netex_framework/netex_reusableComponents/netex_submode_version.xsd
  xsd/netex_framework/netex_reusableComponents/netex_topographicPlace_support.xsd
  xsd/netex_framework/netex_reusableComponents/netex_trainElement_support.xsd
  xsd/netex_framework/netex_reusableComponents/netex_trainElement_version.xsd
  xsd/netex_framework/netex_reusableComponents/netex_vehicleType_version.xsd
  xsd/netex_part_1/part1_frames/netex_siteFrame_version.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_equipmentAccess_version.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_site_version.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_stopPlace_support.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_stopPlace_version.xsd
  xsd/netex_part_1/part1_networkDescription/netex_line_version.xsd
  xsd/netex_part_1/part1_tacticalPlanning/netex_passengerInformationEquipment_version.xsd
  xsd/netex_part_1/part1_tacticalPlanning/netex_routingConstraint_version.xsd
  xsd/netex_part_1/part1_tacticalPlanning/netex_servicePattern_support.xsd
  xsd/netex_part_1/part1_tacticalPlanning/netex_servicePattern_version.xsd
  xsd/netex_part_2/part2_frames/netex_serviceFrame_version.xsd
Labels: needs documentation update

#747 Addition of missing monitored indicator
  xsd/netex_framework/netex_reusableComponents/netex_equipment_version.xsd
  xsd/netex_framework/netex_reusableComponents/netex_vehicleType_version.xsd
  xsd/netex_framework/netex_reusableComponents/netex_vehicle_version.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_parking_version.xsd
Labels: enhancement, needs documentation update, group_decision_needed
