Repository NeTEx-CEN/NeTEx, pull requests merged in 2024-06, with the labels that each got.

#737 Fix Interchangse
  xsd/netex_part_2/part2_journeyTimes/netex_interchangeRule_version.xsd
  xsd/netex_part_2/part2_journeyTimes/netex_interchange_version.xsd
Labels: typo

#741 TypeOfNotice referential constraint fixes
  xsd/NeTEx_publication.xsd
  xsd/NeTEx_publication_timetable.xsd
  xsd/netex_framework/netex_reusableComponents/netex_notice_support.xsd
Labels: bug

#599 AccessRightParameterAssignment - TypeOfProofRef
  examples/functions/newModes/NewModes-CarClubExample.xml
  examples/functions/newModes/NewModes-CarPoolingExample.xml
  xsd/netex_part_3/part3_fares/netex_accessRightParameter_version.xsd
  xsd/netex_part_3/part3_fares/netex_usageParameterEligibility_support.xsd
  xsd/netex_part_3/part3_fares/netex_usageParameterEligibility_version.xsd
Labels: enhancement, needs documentation update
