Repository NeTEx-CEN/NeTEx, pull requests merged in 2024-07, with the labels that each got.

#752 Update netex_ifopt_equipmentAccess_version.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_equipmentAccess_version.xsd
Labels: bug, enhancement, needs documentation update

#744 DeckEntranceAsssignmen and StopAssignment revisions
  NeTEx.spp
  examples/functions/deckPlans/DeckPlans-Example_bus.xml
  examples/functions/deckPlans/DeckPlans-Example_train.xml
  examples/functions/timetable/Netex_21_Rail_NetworkTimetable_eurostar.xml
  examples/standards/epiap/EPIAP_Accessibility_Chur_V08_vehicletypes.xml
  examples/standards/epip/epip_common_profile.xml
  xsd/NeTEx_publication.xsd
  xsd/NeTEx_publication_timetable.xsd
  xsd/netex_framework/netex_reusableComponents/netex_deckPlan_support.xsd
  xsd/netex_framework/netex_reusableComponents/netex_seatingPlan_support.xsd
  xsd/netex_part_1/part1_tacticalPlanning/netex_stopAssignment_support.xsd
  xsd/netex_part_1/part1_tacticalPlanning/netex_stopAssignment_version.xsd
  xsd/netex_part_2/netex_all_objects_part2.xsd
  xsd/netex_part_2/part2_journeyTimes/netex_all_objects_part2_journeyAssignments.xsd
  xsd/netex_part_2/part2_journeyTimes/netex_all_objects_part2_journeyTimes.xsd
  xsd/netex_part_2/part2_journeyTimes/netex_deckEntranceAssignment_support.xsd
  xsd/netex_part_2/part2_journeyTimes/netex_deckEntranceAssignment_version.xsd
  xsd/netex_part_2/part2_journeyTimes/netex_vehicleJourneyStopAssignment_support.xsd
  xsd/netex_part_2/part2_journeyTimes/netex_vehicleJourneyStopAssignment_version.xsd
  xsd/netex_part_2/part2_journeyTimes/netex_vehicleJourney_support.xsd
  xsd/netex_part_2/part2_journeyTimes/netex_vehicleJourney_version.xsd
Labels: change-request, needs documentation update

#620 Enhancement=fare-debit Internal restructuring to enable reuse of payment
  NeTEx.spp
  examples/functions/fares/rail/Netex_era_distance_ro.xml
  xsd/netex_part_3/part3_salesTransactions/netex_customerPaymentMeans_support.xsd
  xsd/netex_part_3/part3_salesTransactions/netex_customerPurchasePackage_version.xsd
  xsd/netex_part_3/part3_salesTransactions/netex_fareDebit_support.xsd
  xsd/netex_part_3/part3_salesTransactions/netex_fareDebit_version.xsd
  xsd/netex_part_3/part3_salesTransactions/netex_salesContract_version.xsd
  xsd/netex_part_3/part3_salesTransactions/netex_salesTransaction_version.xsd
Labels: enhancement

#584 Added CustomerServiceContactDetails and updates Vehicle/VehicleRef
  examples/functions/newModes/NewModes-CarClubExample.xml
  examples/functions/vehicle/Netex_simpleVehicle_01.xml
  xsd/netex_framework/netex_genericFramework/netex_organisation_version.xsd
  xsd/netex_framework/netex_reusableComponents/netex_vehicleType_version.xsd
  xsd/netex_framework/netex_reusableComponents/netex_vehicle_version.xsd
  xsd/netex_part_2/part2_journeyTimes/netex_vehicleJourney_version.xsd
Labels: enhancement, needs documentation update, needs transmodel update

#605 Predicted occupation
  NeTEx.spp
  examples/functions/timetable/Netex_01.1_Bus_SimpleTimetable_JourneysOnly.xml
  examples/functions/timetable/Netex_10_Rail_SplittingJoiningTimetable.xml
  examples/functions/timetable/Netex_51.1_Occupancy.xml
  xsd/NeTEx_publication.xsd
  xsd/netex_part_1/part1_tacticalPlanning/netex_servicePattern_version.xsd
  xsd/netex_part_2/part2_frames/netex_timetableFrame_version.xsd
  xsd/netex_part_2/part2_journeyTimes/netex_call_version.xsd
  xsd/netex_part_2/part2_journeyTimes/netex_coupledJourney_version.xsd
  xsd/netex_part_2/part2_journeyTimes/netex_journey_version.xsd
  xsd/netex_part_2/part2_journeyTimes/netex_passingTimes_version.xsd
  xsd/netex_part_2/part2_occupancy/netex_oc_occupancy_support.xsd
  xsd/netex_part_2/part2_occupancy/netex_oc_occupancy_version.xsd
Labels: enhancement, needs documentation update
