Repository NeTEx-CEN/NeTEx, pull requests merged in 2024-04, with the labels that each got.

#685 Make OrganisationRef abstract
  examples/functions/deprecation/organisationref.xml
  examples/functions/stopPlace/FX-PI-01_UK_TBD_STOP-OFFER_910GWIMBLDN-accessibility_20140601.xml
  examples/functions/stopPlace/Netex_10_StopPlace_uk_ComplexStation_Wimbledon_1.xml
  examples/functions/stopPlace/Netex_10_StopPlace_withParking_1.xml
  examples/functions/timetable/Netex_01.2_Bus_SimpleTimetable_WithTimings.xml
  examples/functions/timetable/Netex_07.2_Bus_FlexibleTimetable_WithPattern.xml
  examples/functions/timetable/Netex_21_Rail_NetworkTimetable_eurostar.xml
  examples/standards/neptune/Le Corbusier - SQYBUS-NeTEx-Profil Arret - External Quays.xml
  examples/standards/neptune/Le Corbusier - SQYBUS-NeTEx-Profil Arret.xml
  examples/standards/norway/stops/OsloS_station_example.xml
  examples/standards/norway/stops/submodel-StationWithEquipment.xml
  xsd/NX.xsd
  xsd/NeTEx_publication_timetable.xsd
  xsd/netex_framework/netex_genericFramework/netex_organisation_version.xsd
  xsd/netex_framework/netex_responsibility/netex_responsibility_support.xsd
  xsd/netex_framework/netex_reusableComponents/netex_otherOrganisation_support.xsd
  xsd/netex_framework/netex_reusableComponents/netex_securityList_version.xsd
  xsd/netex_framework/netex_reusableComponents/netex_transportOrganisation_support.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_site_version.xsd
  xsd/netex_part_1/part1_networkDescription/netex_vehicleAndCrewPoint_version.xsd
  xsd/netex_part_2/part2_journeyTimes/netex_journeyAccounting_version.xsd
  xsd/netex_part_3/part3_fares/netex_calculationParameters_version.xsd
  xsd/netex_part_3/part3_fares/netex_fareProduct_version.xsd
  xsd/netex_part_3/part3_fares/netex_fareStructureElement_version.xsd
  xsd/netex_part_3/part3_fares/netex_fareTable_version.xsd
  xsd/netex_part_3/part3_fares/netex_salesDistribution_version.xsd
  xsd/netex_part_3/part3_salesTransactions/netex_retailConsortium_support.xsd
  xsd/netex_part_3/part3_salesTransactions/netex_retailConsortium_version.xsd
  xsd/netex_part_5/part5_rc/netex_nm_mobilityService_version.xsd
  xsd/netex_part_5/part5_rc/netex_nm_onlineService_support.xsd
Labels: change-request, needs documentation update

#686 Change organisation ref abstract
  .github/scripts/validate-examples.sh
  examples/functions/deprecation/organisationref.xml
  examples/functions/stopPlace/FX-PI-01_UK_TBD_STOP-OFFER_910GWIMBLDN-accessibility_20140601.xml
  examples/functions/stopPlace/Netex_10_StopPlace_uk_ComplexStation_Wimbledon_1.xml
  examples/functions/stopPlace/Netex_10_StopPlace_withParking_1.xml
  examples/functions/timetable/Netex_01.2_Bus_SimpleTimetable_WithTimings.xml
  examples/functions/timetable/Netex_07.2_Bus_FlexibleTimetable_WithPattern.xml
  examples/functions/timetable/Netex_21_Rail_NetworkTimetable_eurostar.xml
  examples/standards/neptune/Le Corbusier - SQYBUS-NeTEx-Profil Arret - External Quays.xml
  examples/standards/neptune/Le Corbusier - SQYBUS-NeTEx-Profil Arret.xml
  examples/standards/norway/stops/OsloS_station_example.xml
  examples/standards/norway/stops/submodel-StationWithEquipment.xml
  xsd/NX.xsd
  xsd/NeTEx_publication_timetable.xsd
  xsd/netex_framework/netex_genericFramework/netex_organisation_version.xsd
  xsd/netex_framework/netex_responsibility/netex_responsibility_support.xsd
  xsd/netex_framework/netex_reusableComponents/netex_otherOrganisation_support.xsd
  xsd/netex_framework/netex_reusableComponents/netex_securityList_version.xsd
  xsd/netex_framework/netex_reusableComponents/netex_transportOrganisation_support.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_site_version.xsd
  xsd/netex_part_1/part1_networkDescription/netex_vehicleAndCrewPoint_version.xsd
  xsd/netex_part_2/part2_journeyTimes/netex_journeyAccounting_version.xsd
  xsd/netex_part_3/part3_fares/netex_calculationParameters_version.xsd
  xsd/netex_part_3/part3_fares/netex_fareProduct_version.xsd
  xsd/netex_part_3/part3_fares/netex_fareStructureElement_version.xsd
  xsd/netex_part_3/part3_fares/netex_fareTable_version.xsd
  xsd/netex_part_3/part3_fares/netex_salesDistribution_version.xsd
  xsd/netex_part_3/part3_salesTransactions/netex_retailConsortium_support.xsd
  xsd/netex_part_3/part3_salesTransactions/netex_retailConsortium_version.xsd
  xsd/netex_part_5/part5_rc/netex_nm_mobilityService_version.xsd
  xsd/netex_part_5/part5_rc/netex_nm_onlineService_support.xsd
Labels: change-request

#612 redid 409 (which also contains 408): Enhancement tMCR Vehicle Equipment profile Member, accepted driver permits
  examples/functions/newModes/NewModes-CycleSharingExample.xml
  xsd/NeTEx_publication.xsd
  xsd/netex_framework/netex_reusableComponents/netex_vehicleType_support.xsd
  xsd/netex_framework/netex_reusableComponents/netex_vehicleType_version.xsd
Labels: bug

#464 Adding unique constraints for the elements that actually exists in our examples
  examples/functions/timetable/Netex_01.4_Bus_SimpleTimetable_WithConnection.xml
  examples/functions/timetable/Netex_07.2_Bus_FlexibleTimetable_WithPattern.xml
  examples/functions/versioning/Netex_Uniqueness_01.xml
  xsd/NeTEx_publication.xsd
  xsd/NeTEx_publication_timetable.xsd
Labels: bug

#708 PublicCodeStructure instead PublicCodeType
  xsd/netex_framework/netex_genericFramework/netex_organisation_version.xsd
  xsd/netex_framework/netex_genericFramework/netex_zone_version.xsd
  xsd/netex_framework/netex_reusableComponents/netex_equipment_version.xsd
  xsd/netex_framework/netex_reusableComponents/netex_notice_version.xsd
  xsd/netex_framework/netex_utility/netex_utility_types.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_flexibleStopPlace_version.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_parking_support.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_site_version.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_stopPlace_support.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_stopPlace_version.xsd
  xsd/netex_part_1/part1_networkDescription/netex_line_version.xsd
  xsd/netex_part_1/part1_tacticalPlanning/netex_servicePattern_version.xsd
Labels: change-request

#683 Introduce the examples from Norway & change Covered from boolean to enumeration
  examples/standards/norway/vehicles/submodel-VehicleType.xml
  xsd/netex_framework/netex_reusableComponents/netex_environment_support.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_equipmentParking_version.xsd
Labels: enhancement, needs documentation update, UML update needed

#712 More information to PassengerStopAssignment usage
  xsd/netex_part_1/part1_tacticalPlanning/netex_stopAssignment_version.xsd
Labels: change-request
