Repository NeTEx-CEN/NeTEx, pull requests merged in 2024-10, with the labels that each got.

#786 Remove one Description from PathLinkInSequenceGroup
  examples/functions/site/Netex_01_Sites_SimpleStadium_1.xml
  examples/functions/site/Netex_10_Sites_OlympicPark_2_basic.xml
  examples/functions/site/Netex_11_Sites_OlympicPark_1.xml
  examples/functions/stopPlace/FX-PI-01_UK_TBD_STOP-OFFER_910GWIMBLDN-accessibility_20140601.xml
  examples/functions/stopPlace/Netex_04_Stops_SimpleStation_1.xml
  examples/functions/stopPlace/Netex_10_StopPlace_uk_ComplexStation_Wimbledon_1.xml
  examples/functions/stopPlace/Netex_10_StopPlace_withParking_1.xml
  xsd/netex_framework/netex_genericFramework/netex_path_version.xsd
Labels: change-request, needs documentation update

#731 RestrictedServiceFacilityRef in ServiceJourney/facilities with a restriction in an AvailabilityCondition and From/To in Calls an StopPointsInJourneyPattern. and fixed missing CallRef
  NeTEx.spp
  examples/functions/newModes/NewModes-ChauffeuredServiceExample.xml
  xsd/NeTEx_publication.xsd
  xsd/netex_framework/netex_reusableComponents/netex_facility_support.xsd
  xsd/netex_framework/netex_reusableComponents/netex_facility_version.xsd
  xsd/netex_framework/netex_reusableComponents/netex_mode_support.xsd
  xsd/netex_part_2/part2_frames/netex_timetableFrame_version.xsd
  xsd/netex_part_2/part2_journeyTimes/netex_all_objects_part2_journeyTimes.xsd
  xsd/netex_part_2/part2_journeyTimes/netex_call_support.xsd
  xsd/netex_part_2/part2_journeyTimes/netex_journey_facility_support.xsd
Labels: enhancement, needs documentation update, UML update needed

#792 Remove unused chargingEquipmenProfilesInFrame_RelStructure
  xsd/netex_framework/netex_reusableComponents/netex_nm_chargingEquipmentProfile_version.xsd
Labels: bug, document has been updated

#794 Annotation to version attribute
  xsd/netex_framework/netex_responsibility/netex_version_support.xsd
Labels: enhancement, needs documentation update
