Repository NeTEx-CEN/NeTEx, pull requests merged in 2024-02, with the labels that each got.

#645 Fix DatedServiceJourney for TAP TSI examples
  examples/standards/era_uic/Netex_Eurostar mapping_era_1.xml
  examples/standards/era_uic/Netex_Eurostar mapping_era_2.xml
  examples/standards/era_uic/Netex_era_uic_calendar.xml
  examples/standards/era_uic/Netex_era_uic_joiningsplitting.xml
  examples/standards/era_uic/Netex_era_uic_simpletimetable.xml
  examples/standards/era_uic/Netex_era_uic_timetable_hack_01.xml
  examples/standards/tap_tsi/TAP-SKDUPD-example1-basic.xml
  examples/standards/tap_tsi/TAP-SKDUPD-example1.xml
  examples/standards/tap_tsi/TAP-SKDUPD-example2.1-Classic_train.xml
  examples/standards/tap_tsi/TAP-SKDUPD-example2.2-Coach_group.xml
  examples/standards/tap_tsi/TAP-SKDUPD-example2.3-Leo_Express.xml
  examples/standards/tap_tsi/TAP-SKDUPD-example2.4-Load_and_Unload.xml
  examples/standards/tap_tsi/TAP-SKDUPD-example2.5-Interchange.xml
  examples/standards/tap_tsi/TAP-SKDUPD-example2.6-Check_In.xml
  examples/standards/tap_tsi/TAP-SKDUPD-example2.7-Tariff_and_Reservation.xml
  examples/standards/tap_tsi/TAP-SKDUPD-example2.7-Tarrif_and_Reservation.xml
  examples/standards/tap_tsi/TAP-SKDUPD-example2.xml
Labels: bug

#633 Site Entrance qualifier (on next)
  examples/functions/stopPlace/Netex_10_StopPlace_withParking_1.xml
  xsd/netex_part_1/part1_ifopt/netex_ifopt_site_support.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_site_version.xsd
Labels: enhancement

#634 LiftCallEquipment
  xsd/NeTEx_publication.xsd
  xsd/NeTEx_publication_timetable.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_equipmentAccess_support.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_equipmentAccess_version.xsd
Labels: enhancement

#555 EPIAP Equipments Enhancement
  xsd/netex_framework/netex_reusableComponents/netex_mode_support.xsd
  xsd/netex_framework/netex_reusableComponents/netex_nm_equipmentEnergy_support.xsd
  xsd/netex_framework/netex_reusableComponents/netex_submode_version.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_equipmentAccess_support.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_equipmentAccess_version.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_equipmentPassenger_support.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_equipmentPassenger_version.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_equipmentWaiting_version.xsd
Labels: enhancement, needs documentation update

#664 `TactileWriting` attribute for all handrails
  xsd/netex_part_1/part1_ifopt/netex_ifopt_equipmentAccess_version.xsd
Labels: enhancement

#513 Revert new modes StopPlace_ abstract on stopPlacesInFrame_RelStructure
  examples/functions/newModes/NewModes-CarPoolingExample.xml
  examples/functions/newModes/NewModes-ChauffeuredServiceExample.xml
  xsd/netex_part_1/part1_frames/netex_siteFrame_version.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_stopPlace_version.xsd
  xsd/netex_part_1/part1_ifopt/netex_taxiPlace_version.xsd
Labels: bug, change-request, needs documentation update

#655 removing xpath to DeadRunServicePattern and DeadRunPattern
  xsd/NeTEx_publication.xsd
  xsd/NeTEx_publication_timetable.xsd
Labels: bug

#570 Documentation - Enhancement Readme
  README.md
  change_log.md
Labels: enhancement

#449 Prefix netex as namespace of DistributionGroupRef
  examples/functions/fares/Netex_101.21_TfL_GeographicFares_UnitZone_MultipleProduct.xml
  examples/functions/newModes/NewModes-CarClubExample.xml
  examples/standards/fxc/FX-PI-01_UK_FBRI_LINE-FARE_WOE-Bristol-Line-48-trip-(stage)_2017-01-01.xml
  examples/standards/fxc/FX-PI-01_UK_FBRI_NETWORK-FARE_WOE-Bristol-pass-(Z2Z)_2017-01-01.xml
  xsd/NeTEx_publication.xsd
  xsd/NeTEx_publication_timetable.xsd
Labels: bug
