Repository NeTEx-CEN/NeTEx, pull requests merged in 2024-05, with the labels that each got.

#462 Remove all abstract elements from constraint validation
  xsd/NeTEx_publication.xsd
  xsd/NeTEx_publication_timetable.xsd
  xsd/netex_framework/netex_responsibility/netex_responsibilitySet_version.xsd
Labels: bug

#696 Add properties to describe the height of a Lift
  xsd/netex_part_1/part1_ifopt/netex_ifopt_equipmentAccess_version.xsd
Labels: change-request

#722 Fix typo
  xsd/netex_framework/netex_reusableComponents/netex_vehicleType_version.xsd
Labels: typo

#720 Update neTactileActuators attribute on Escalators and Travelators #665tex_ifopt_equipmentAccess_version.xsd
  xsd/netex_part_1/part1_ifopt/netex_ifopt_equipmentAccess_version.xsd
Labels: bug

#724 Update netex_facility_support.xsd
  xsd/netex_framework/netex_reusableComponents/netex_facility_support.xsd
Labels: change-request, document has been updated

#723 TypeOfEntity is abstract
  xsd/NeTEx_publication.xsd
  xsd/NeTEx_publication_timetable.xsd
Labels: bug

#623 fixing imports to make files validate (multilingualstring)
  xsd/netex_framework/netex_responsibility/netex_entity_version.xsd
  xsd/netex_framework/netex_responsibility/netex_versionDelta_version.xsd
Labels: bug

#715 Improve docu for id in StopPlace (as it is always a discussion point).
  xsd/netex_part_1/part1_ifopt/netex_ifopt_stopPlace_version.xsd
Labels: enhancement

#714 Order attribute in documentation on FareTableColumn and FareTableRow missing
  xsd/netex_part_3/part3_fares/netex_fareTable_version.xsd
Labels: bug

#639 Fix passenger category change for line modularisation
  NeTEx.spp
  examples/functions/simpleNetwork/Netex_LineClassification_1.xml
  xsd/netex_framework/netex_reusableComponents/netex_serviceRestrictions_support.xsd
  xsd/netex_part_1/part1_networkDescription/netex_line_version.xsd
  xsd/netex_part_3/part3_fares/netex_usageParameterEligibility_support.xsd
Labels: change-request, needs documentation update

#730 GBFSMapping - mustPickUpandDRopOffToSameStop #716
  examples/standards/gbfs/Netex_gbfs_exm1.xml
  xsd/netex_part_1/part1_tacticalPlanning/netex_routingConstraint_support.xsd
  xsd/netex_part_5/part5_nd/netex_nm_mobilityServiceConstraintZone_support.xsd
  xsd/netex_part_5/part5_nd/netex_nm_mobilityServiceConstraintZone_version.xsd
Labels: enhancement

#727 Propose change for TypeOfFrameRef
  xsd/netex_framework/netex_responsibility/netex_versionFrame_version.xsd
Labels: bug
