Repository NeTEx-CEN/NeTEx, pull requests merged in 2025-04, with the labels that each got.

#813 Seating Plan Seat Context changes
  examples/functions/deckPlans/DeckPlans-Example_bus.xml
  examples/functions/deckPlans/DeckPlans-Example_train.xml
  xsd/netex_framework/netex_reusableComponents/netex_seatingPlan_support.xsd
  xsd/netex_framework/netex_reusableComponents/netex_seatingPlan_version.xsd
Labels: change-request, needs documentation update

#845 Adding noTicketRequired-enum
  xsd/netex_framework/netex_reusableComponents/netex_serviceRestrictions_support.xsd
Labels: enhancement, needs documentation update

#847 A few corrections part 2
  xsd/netex_part_1/part1_tacticalPlanning/netex_timeDemandType_version.xsd
  xsd/netex_part_2/part2_journeyTimes/netex_coupledJourney_version.xsd
  xsd/netex_part_2/part2_journeyTimes/netex_datedPassingTimes_version.xsd
  xsd/netex_part_2/part2_journeyTimes/netex_interchange_version.xsd
  xsd/netex_part_2/part2_journeyTimes/netex_journeyAccounting_version.xsd
  xsd/netex_part_2/part2_journeyTimes/netex_serviceJourney_version.xsd
  xsd/netex_part_2/part2_vehicleService/netex_duty_version.xsd
  xsd/netex_part_2/part2_vehicleService/netex_vehicleService_version.xsd
  xsd/netex_part_3/part3_monitoring/netex_monitoredPassingTimes_version.xsd
Labels: bug, needs documentation update, fix_now

#852 PrintColourValueType
  xsd/netex_framework/netex_utility/netex_utility_types.xsd
Labels: bug, needs documentation update, fix_now

#848 Estimated delay in timetable
  NeTEx.spp
  examples/functions/timetable/Netex_52_planned_delay.xml
Labels: needs documentation update, fix_now

#868 Make DirectionType uniform (for an uniform binding interface)
  xsd/netex_part_1/part1_tacticalPlanning/netex_journeyPattern_version.xsd
Labels: hygiene

#871 Deprecate BaselineVersionRef
  examples/functions/timetable/Netex_08.2_Bus_SimpleTimetable_Cancellation.xml
  examples/functions/timetable/Netex_09.1_Bus_InterchangeRule.xml
  examples/functions/variant/Netex_VariantExample_Step_05.xml
  examples/functions/versioning/Netex_VersioningExample_Step_03.xml
  examples/functions/versioning/Netex_VersioningExample_Step_04.xml
  examples/functions/versioning/Netex_VersioningExample_Step_05.xml
  examples/functions/versioning/Netex_VersioningExample_Step_05_ByRef.xml
  examples/functions/versioning/Netex_VersioningExample_Step_05_GeneralFrame.xml
  examples/standards/vdv452/calendar/Netex_de_calendarExample_01_gd.xml
  xsd/netex_framework/netex_responsibility/netex_versionFrame_version.xsd
Labels: needs documentation update, hygiene

#867 Remove duplicate PassingTimeRefStructure
  xsd/netex_part_2/part2_journeyTimes/netex_passengerAtStopTimes_support.xsd
Labels: hygiene

#861 Merge of FlexibleLineType into LineType
  xsd/netex_part_1/part1_networkDescription/netex_flexibleNetwork_support.xsd
  xsd/netex_part_1/part1_networkDescription/netex_flexibleNetwork_version.xsd
  xsd/netex_part_1/part1_networkDescription/netex_line_support.xsd
  xsd/netex_part_1/part1_networkDescription/netex_line_version.xsd
  xsd/netex_part_2/part2_journeyTimes/netex_serviceJourney_version.xsd
Labels: needs documentation update

#849 MultilingualString with embedded translations
  examples/functions/versioning/Netex_VersioningExample_Step_05.xml
  xsd/netex_framework/netex_genericFramework/netex_alternativeName_support.xsd
  xsd/netex_framework/netex_utility/netex_utility_xml.xsd
Labels: change-request, needs documentation update, fix_now

#879 Corrections to includes to fix missing to dependencies
  xsd/netex_part_1/part1_networkDescription/netex_line_version.xsd
  xsd/netex_part_2/part2_journeyTimes/netex_call_version.xsd
  xsd/netex_part_3/part3_fares/netex_accessRightParameter_version.xsd
  xsd/netex_part_3/part3_salesTransactions/netex_travelSpecificationSummary_version.xsd
Labels: bug
