Repository NeTEx-CEN/NeTEx, pull requests merged in 2025-02, with the labels that each got.

#828 Update netex_flexibleNetwork_support.xsd
  xsd/netex_part_1/part1_networkDescription/netex_flexibleNetwork_support.xsd
Labels: enhancement

#830 TrainBlock and TrainBlockPart definition update
  xsd/netex_part_2/part2_journeyTimes/netex_coupledJourney_support.xsd
  xsd/netex_part_2/part2_vehicleService/netex_vehicleService_version.xsd
Labels: needs documentation update

#823 Addition of neigbouring to SameZoneEnumeration
  xsd/netex_part_3/part3_fares/netex_usageParameterEntitlement_support.xsd
Labels: needs documentation update

#832 Update enums in netex_facility_support.xsd
  xsd/netex_framework/netex_reusableComponents/netex_facility_support.xsd
Labels: needs documentation update

#835 Fix OppositeDirectionRef in master
  xsd/NeTEx_publication.xsd
  xsd/NeTEx_publication_timetable.xsd
Labels: bug
