Repository NeTEx-CEN/NeTEx, pull requests merged in 2025-06, with the labels that each got.

#911 Fix minor spelling mistakes in SpotAffinityTypeEnumeration
  xsd/netex_framework/netex_reusableComponents/netex_spotAffinity_support.xsd
Labels: typo

#909 SeatContext proposal
  examples/functions/deckPlans/DeckPlans-Example.xml
  examples/functions/deckPlans/DeckPlans-Example_bus.xml
  examples/functions/deckPlans/DeckPlans-Example_train.xml
  examples/functions/deckPlans/DeckPlans-Example_train_simple.xml
  xsd/netex_framework/netex_reusableComponents/netex_seatingPlan_support.xsd
  xsd/netex_framework/netex_reusableComponents/netex_seatingPlan_version.xsd
Labels: needs documentation update, hygiene

#917 Remove redundant Description
  xsd/netex_part_2/part2_journeyTimes/netex_deckEntranceAssignment_version.xsd
  xsd/netex_part_2/part2_journeyTimes/netex_vehicleJourneyFrequency_version.xsd
Labels: bug, needs documentation update

#926 Entrance deprecation as instance
  xsd/netex_part_1/part1_ifopt/netex_ifopt_site_version.xsd
Labels: document has been updated

#925 MandatoryEnumeration comment correction
  xsd/netex_framework/netex_responsibility/netex_entity_support.xsd
Labels: bug, document has been updated
